# Generated by Django 6.0.7 on 2026-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='representative_role',
            field=models.CharField(default='HR', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(default='Level 3', max_length=50),
            preserve_default=False,
        ),
    ]
